name: Build for aarch64

on: [push, pull_request]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc-aarch64-linux-gnu pkg-config libfluidsynth-dev

    - name: Build for aarch64
      run: |
        export CC=aarch64-linux-gnu-gcc
        make
